#! /bin/sh

case "$1" in
        start)
                start-stop-daemon -S -n module_load -a /usr/bin/module_load -- faulty
                start-stop-daemon -S -n scull_load -a /usr/bin/scull_load                
                modprobe hello
                ;;

        stop)
                start-stop-daemon -S -n module_unload -a /usr/bin/module_unload -- faulty
                start-stop-daemon -S -n scull_unload -a /usr/bin/scull_unload
                rmmod hello
                ;;
        *)
                echo "Usage : $0 {start|stop}"
        exit 1
esac
